# Generated by Django 6.0.1 on 2026-01-27 06:01

from django.db import migrations

def _column_exists(cursor, table, column):
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = %s
          AND COLUMN_NAME = %s
        """,
        [table, column],
    )
    return cursor.fetchone()[0] > 0


def add_consultation_fields(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if _column_exists(cursor, 'doctors_consultationrequest', 'report'):
            cursor.execute("ALTER TABLE doctors_consultationrequest DROP COLUMN report")
        if not _column_exists(cursor, 'doctors_consultationrequest', 'consultation_fee'):
            cursor.execute(
                "ALTER TABLE doctors_consultationrequest "
                "ADD COLUMN consultation_fee DECIMAL(10,2) NOT NULL DEFAULT 0"
            )
        if not _column_exists(cursor, 'doctors_consultationrequest', 'payment_status'):
            cursor.execute(
                "ALTER TABLE doctors_consultationrequest "
                "ADD COLUMN payment_status VARCHAR(20) NOT NULL DEFAULT 'Pending'"
            )


def remove_consultation_fields(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if _column_exists(cursor, 'doctors_consultationrequest', 'payment_status'):
            cursor.execute("ALTER TABLE doctors_consultationrequest DROP COLUMN payment_status")
        if _column_exists(cursor, 'doctors_consultationrequest', 'consultation_fee'):
            cursor.execute("ALTER TABLE doctors_consultationrequest DROP COLUMN consultation_fee")
        if not _column_exists(cursor, 'doctors_consultationrequest', 'report'):
            cursor.execute("ALTER TABLE doctors_consultationrequest ADD COLUMN report VARCHAR(100) NULL")


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('doctors', '0003_appointment_consultationrequest_prescription'),
    ]

    operations = [
        migrations.RunPython(add_consultation_fields, remove_consultation_fields),
    ]
