# Generated by Django 6.0 on 2026-02-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_consultationrequest_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
