# Generated by Django 6.0 on 2026-02-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_delete_consultationpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='related_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
